geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp
app_name = 'authapp'
urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
]

geekshop/geekshop/urls.py
from django.urls import path
from django.contrib import admin
from mainapp import views

urlpatterns = [
    path('', views.main),
    path('products/', views.products),
    path('contact/', views.contact),
#    path('admin/', admin.site.urls),
]

geekshop/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'
urlpatterns = [
    path('', mainapp.products, name='index'),
    path('<int:pk>/', mainapp.products, name='category'),
]

geekshop/mainapp/models.py
from django.db import models

# Create your models here.

geekshop/mainapp/views.py
from django.shortcuts import render

# Create your views here.
def main(request):
    return render(request, 'index.html')


def products(request):
    return render(request, 'products.html')


def contact(request):
    return render(request, 'contact.html')

geekshop/mainapp/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <title>
        {{ title.name|title }} -Магазин, Сегодня: {% now 'd.m.Y' %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
	<div class="container">
        {% block menu %}

        {% endblock %}

        {% block content %}

        {% endblock %}
    </div>

    <div class="footer">
        {% block footer %}
            <div class="clearfix">
                <div class="text-footer">
                    <h3>контакты</h3>
                </div>
                <div class="text-footer">
                    <h3>полезная информация</h3>
                </div>
                <div class="text-footer clearfix">
                    <h3>Оставайтесь на связи</h3>
                    <p>Подписаться на новости и рассылки</p>
                    <form>
                        <input type="email" name="email" placeholder="ваш email">
                        <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                    </form>
                </div>
            </div>
        {% endblock %}
    </div>
</body>
</html>

geekshop/mainapp/templates/contact.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Контакты</title>
	<link rel="stylesheet" type="text/css" href="/static/style.css">
	<link rel="stylesheet" href="/static/fonts/font-awesome/css/font-awesome.css">
</head>
<body>
	<div class="container">
		<div class="hero">
			<div class="header clearfix">
				<a href="index.html" class="logo"></a>
				<ul class="menu">
					<li><a href="/">домой</a></li>
					<li><a href="/products/">продукты</a></li>
					<li><a href="/contact/" class="active">контакты</a></li>
				</ul>
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
			<h1>наши контакты</h1>
		</div>

		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

		<div class="clr"></div>
	</div>	

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>	
			
</body>
</html>

geekshop/mainapp/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Магазин</title>
	<link rel="stylesheet" type="text/css" href="static/style.css">
	<link rel="stylesheet" href="static/fonts/font-awesome/css/font-awesome.css">
</head>
<body>
	<div class="container">
		<div class="slider">
			<div class="header clearfix">
				<a href="index.html" class="logo"></a>
				<ul class="menu">
					<li><a href="/" class="active">домой</a></li>
					<li><a href="/products/">продукты</a></li>
					<li><a href="/contact/">контакты</a></li>
				</ul>
				<a href="#" class="search"></a>
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="static/img/arrow.png" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>

		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="static/img/arrow.png" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				<div class="block">
					<a href="#"><img src="static/img/product-1.jpg" alt="">
						<div class="text">
							<img src="img/icon-hover.png" alt="img">
							<h4>Отличный стул</h4>
							<p>Расположитесь комфортно. </p>
						</div> 
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="static/img/product-2.jpg" alt="">
						<div class="text">
							<img src="static/img/icon-hover.png" alt="">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>	
			</div>
		</div>
		
		<div class="clr"></div>

	</div>

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>	
	
</body>
</html>

geekshop/mainapp/templates/product.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
      <div class="details-slider">
        <div class="slider-product">
          <img src="/media/{{ product.image }}"
               alt="{{ product.short_desc }}">
        </div>
        <div class="slider-control">
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 1">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 2">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 3">
            </a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ product.name }}</h3>
        <br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
          заказать
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ product.description }}
        </div>
      </div>
    </div>

  </div>

  <div class="clr"></div>
{% endblock %}

geekshop/mainapp/templates/products.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Каталог</title>
	<link rel="stylesheet" href="/static/style.css">
	<link rel="stylesheet" href="/static/fonts/font-awesome/css/font-awesome.css">
</head>
<body>
	<div class="container">
		<div class="hero-white">
			<div class="header clearfix">
				<a href="index.html" class="logo"></a>
				<ul class="menu">
					<li><a href="/">домой</a></li>
					<li><a href="/products/" class="active">продукты</a></li>
					<li><a href="/contact/">контакты</a></li>

				</ul>
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
		</div>

		<div class="details">
			<div class="links clearfix">
				<ul class="links-menu">
					<li><a href="#" class="active">все</a></li>
					<li><a href="#">дом</a></li>
					<li><a href="#">офис</a></li>
					<li><a href="#">модерн</a></li>
					<li><a href="#">классика</a></li>
				</ul>
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="/static/img/slider1.jpg">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="/static/img/controll.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/static/img/controll1.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="static/img/controll2.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">Отличный стул</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> 2585.9 <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>Расположитесь комфортно.</p> 
						<p>Отличное качество материалов
						позволит вам это.</p> 
						<p>Различные цвета</p>
						<p>высочайший уровень
						эргономики и прочность.</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="/static/img/product-11.jpg" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/static/img/product-21.jpg" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/static/img/product-31.jpg" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>

		<div class="clr"></div>

	</div>	

	<div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>	

</body>
</html>

geekshop/mainapp/templates/products_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block menu %}
  <div class="hero-white">
    <div class="header clearfix">
      {% include 'includes/inc_menu.html' %}
    </div>
  </div>
{% endblock %}
{% block content %}
  <div class="details">
      {% include 'includes/inc_categories_menu.html' %}

    <div class="products_list">
      <div class="title clearfix">
        <h2>
          Категория: "{{ category.name|title }}"
        </h2>
      </div>
      <div class="related-products clearfix">

        {% for product in products %}
          <div class="block">
            <a href="{% url 'basket:add' product.pk %}">
              <img src="/media/{{ product.image }}" alt="{{product.short_desc}}">
              <div class="text">
                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                  <h4>{{ product.name }}</h4>
                  <p>{{ product.description }}</p>
              </div>
            </a>
          </div>
        {% endfor %}

      </div>
    </div>
  </div>

  <div class="clr"></div>

{% endblock %}